version: "3"

networks:
  todo-svc:

services:
  php:
    # image: php:8.0.5-fpm-alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./src:/src
    networks:
      - todo-svc

  nginx:
    image: nginx:1.21.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - todo-svc

  mariadb:
    image: mariadb:10.7.1
    ports:
      - "3305:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - todo-svc
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
